import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/ui/sidebar'
import Header from '@/components/Header'
import Provider from '@/app/(general)/providers'
import { options } from '../api/auth/[...nextauth]/options'
import { getServerSession } from 'next-auth'
import AuthenticationPage from '../(auth)/signin/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>


        <div className="flex h-screen overflow-hidden">
          <Provider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            {/* <!-- ===== Sidebar Start ===== --> */}
            <Sidebar
            />
            {/* <!-- ===== Sidebar End ===== --> */}



            {/* <!-- ===== Content Area Start ===== --> */}
            <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
              {/* <!-- ===== Header Start ===== --> */}
              <Header />
              {/* <!-- ===== Header End ===== --> */}

              {/* <!-- ===== Main Content Start ===== --> */}
              <main>
                <div className="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10">


                  {children}


                </div>
              </main>
              {/* <!-- ===== Main Content End ===== --> */}
            </div>
            {/* <!-- ===== Content Area Start ===== --> */}

          </Provider>
        </div>


        {/* Implement loading... */}



      </body>
    </html >
  )
}
