import React from 'react';
import {
  Plane, // Flight
  Dumbbell, // Super Strength
  Zap, // Superspeed
  Footprints,
  // Footprints, // 
  ShieldCheckIcon,
  BrainCircuit,
  Wand2,
  Brain, //
  Sparkles, // teleport
  RadarIcon,
  EyeIcon,
  ShieldIcon,
  Flame,
  ActivitySquare, // healing
  Wand, // 
  SwordIcon,
  Cigarette,
  EarIcon,
  EyeOff,
  GhostIcon,
  Palette,
  Rotate3d,
  MagnetIcon,
  // Flame, // FireControl
  Cpu,
  Cat,
  BrainIcon,
  Landmark,
  Briefcase,
  RadiationIcon,
  Spline,
  Grab,
  PocketKnife,
  CloudSunIcon,
  SunMoon,
  Pipette,
  Scaling,
  InfinityIcon,
  SkullIcon,
  HeartPulse,
  CloudLightning,
  SnowflakeIcon,
  AnchorIcon,
  Mountain,
  HelpCircle,
  Volume2,
  KeyIcon,
  LucideIcon,
} from 'lucide-react';

//  const Superpowers = {
//   Flight: Plane,
//   SuperStrength: Dumbbell,
//   SuperSpeed: Zap,
//   Agility: Footprints,
//   Stamina: Footprints,
//   Invulnerability: ShieldCheckIcon,
//   Telepathy : BrainCircuit,
//   Telekinesis : Wand2,
//   Intellect : Brain,
//   Teleport : Sparkles,
//   RadarSense : RadarIcon,
//   Psychic : EyeIcon,
//   ForceField : ShieldIcon,
//   BlastPower : Flame,
//   Healing : ActivitySquare, 
//   Magic : Wand,
//   WeaponMaster : SwordIcon,
//   SuperSight : EyeIcon,
//   SuperSmell : Cigarette,
//   SuperHearing : EarIcon,
//   Invisibility : EyeOff,
//   PhasingGhost : GhostIcon,
//   Chameleon : Palette,
//   ShapeShifter : Rotate3d,
//   Magnetism : MagnetIcon,
//   FireControl : Flame,
//   Implants : Cpu,
//   Feral : Cat,
//   Psionic : BrainIcon,
//   InsanelyRich : Landmark,
//   PowerSuit : Briefcase,
//   Radiation : RadiationIcon,
//   Elasticity : Spline,
//   UnarmedCombat : Grab,
//   Gadgets : PocketKnife,
//   WeatherControl : CloudSunIcon,
//   DivinePowers : SunMoon,
//   SiphonAbilities : Pipette,
//   SizeManipulation : Scaling,
//   Immortal : InfinityIcon,
//   Necromancy : SkullIcon,
//   Vampirism : HeartPulse,
//   ElectricityControl : CloudLightning,
//   IceControl : SnowflakeIcon,
//   SubMariner : AnchorIcon,
//   WallClinger : Mountain,
//   Mesmerize : HelpCircle,
//   PenanceStare : EyeIcon,
//   SonicScream : Volume2,
//   EscapeArtist : KeyIcon,
// }

// Define a Map mapping superpowers to their respective icons


const SuperpowersMap = new Map<string, LucideIcon>([
  ['Flight', Plane],
  ['SuperStrength', Dumbbell],
  ['SuperSpeed', Zap],
  ['Agility', Footprints],
  ['Stamina', Footprints],
  ['Invulnerability', ShieldCheckIcon],
  ['Telepathy', BrainCircuit],
  ['Telekinesis', Wand2],
  ['Intellect', Brain],
  ['Teleport', Sparkles],
  ['RadarSense', RadarIcon],
  ['Psychic', EyeIcon],
  ['ForceField', ShieldIcon],
  ['BlastPower', Flame],
  ['Healing', ActivitySquare],
  ['Magic', Wand],
  ['WeaponMaster', SwordIcon],
  ['SuperSight', EyeIcon],
  ['SuperSmell', Cigarette],
  ['SuperHearing', EarIcon],
  ['Invisibility', EyeOff],
  ['PhasingGhost', GhostIcon],
  ['Chameleon', Palette],
  ['ShapeShifter', Rotate3d],
  ['Magnetism', MagnetIcon],
  ['FireControl', Flame],
  ['Implants', Cpu],
  ['Feral', Cat],
  ['Psionic', BrainIcon],
  ['InsanelyRich', Landmark],
  ['PowerSuit', Briefcase],
  ['Radiation', RadiationIcon],
  ['Elasticity', Spline],
  ['UnarmedCombat', Grab],
  ['Gadgets', PocketKnife],
  ['WeatherControl', CloudSunIcon],
  ['DivinePowers', SunMoon],
  ['SiphonAbilities', Pipette],
  ['SizeManipulation', Scaling],
  ['Immortal', InfinityIcon],
  ['Necromancy', SkullIcon],
  ['Vampirism', HeartPulse],
  ['ElectricityControl', CloudLightning],
  ['IceControl', SnowflakeIcon],
  ['SubMariner', AnchorIcon],
  ['WallClinger', Mountain],
  ['Mesmerize', HelpCircle],
  ['PenanceStare', EyeIcon],
  ['SonicScream', Volume2],
  ['EscapeArtist', KeyIcon],
]);

export default SuperpowersMap;
